Upgrade to NDK r8b and 64-bit toolchain

diff --git a/ndk/ndk-gdb b/ndk/ndk-gdb
--- a/ndk/ndk-gdb
+++ b/ndk/ndk-gdb
@@ -28,10 +28,40 @@
 
 force_32bit_binaries
 
-find_program ADB_CMD adb
-ADB_FLAGS=
+# Find if a given shell program is available.
+# We need to take care of the fact that the 'which <foo>' command
+# may return either an empty string (Linux) or something like
+# "no <foo> in ..." (Darwin). Also, we need to redirect stderr
+# to /dev/null for Cygwin
+#
+# $1: program name
+# Out: program path, or empty string
+# Return: 0 on success, != 0 on error
+#
+find_program ()
+{
+    local PROG RET
+    PROG=$(which "$1" 2>/dev/null)
+    RET=$?
+    if [ $RET != 0 ]; then
+        PROG=
+    fi
+    echo "$PROG"
+    return $RET
+}
 
-AWK_CMD=awk
+quote_spaces ()
+{
+    echo "$@" | sed -e 's! !\ !g'
+}
+
+# If ADB_CMD is not defined, try to find a program named 'adb'
+# in our path.
+ADB_CMD=${ADB_CMD:-$(find_program adb)}
+ADB_FLAGS=${ADB_FLAGS:-}
+DEVICE_SERIAL=
+
+AWK_CMD=${AWK_CMD:-$(find_program awk)}
 
 DEBUG_PORT=5039
 
@@ -143,13 +173,15 @@ while [ -n "$1" ]; do
         -s)
             check_parameter $1 $2
             check_adb_flags
-            ADB_FLAGS=" -s $2"
+            ADB_FLAGS=" -s"
+            DEVICE_SERIAL=$2
             shift
             ;;
         -s*)
             check_adb_flags
             optarg=`expr -- "$opt" : '-s\(.*\)'`
-            ADB_FLAGS=" -s $optarg"
+            ADB_FLAGS=" -s"
+            DEVICE_SERIAL=$optarg
             ;;
         -p)
             check_parameter $1 $2
@@ -266,7 +298,7 @@ fi
 
 # Check ADB tool version
 if [ -n "$OPTION_ADB" ] ; then
-    ADB_CMD="$OPTION_ADB"
+    ADB_CMD=$OPTION_ADB
     log "Using specific adb command: $ADB_CMD"
 else
     if [ -z "$ADB_CMD" ] ; then
@@ -278,16 +310,31 @@ else
     log "Using default adb command: $ADB_CMD"
 fi
 
-ADB_VERSION=`$ADB_CMD version`
+ADB_CMD=$(quote_spaces $ADB_CMD)
+ADB_VERSION=$("$ADB_CMD" version 2>/dev/null)
 if [ $? != 0 ] ; then
     echo "ERROR: Could not run ADB with: $ADB_CMD"
     exit 1
 fi
 log "ADB version found: $ADB_VERSION"
 
-ADB_CMD="${ADB_CMD}${ADB_FLAGS}"
-log "Using final ADB command: '$ADB_CMD'"
+if [ "x$DEVICE_SERIAL" = "x" ]; then
+    log "Using ADB flags: $ADB_FLAGS"
+else
+    log "Using ADB flags: $ADB_FLAGS" \"$DEVICE_SERIAL\"
+fi
 
+# Run an ADB command with the right ADB flags
+# $1+: adb command parameter
+adb_cmd ()
+{
+    if [ "x$DEVICE_SERIAL" = "x" ]; then
+        "$ADB_CMD" $ADB_FLAGS "$@"
+    else
+        # NOTE: We escape $ADB_CMD and $DEVICE_SERIAL in case they contains spaces.
+        "$ADB_CMD" $ADB_FLAGS "$DEVICE_SERIAL" "$@"
+    fi
+}
 
 # Used internally by adb_var_shell and adb_var_shell2.
 # $1: 1 to redirect stderr to $1, 0 otherwise.
@@ -304,9 +351,9 @@ _adb_var_shell ()
     # Run the command, while storing the standard output to CMD_OUT
     # and appending the exit code as the last line.
     if [ "$REDIRECT_STDERR" != 0 ]; then
-        $ADB_CMD shell $@ ";" echo \$? | sed -e 's![[:cntrl:]]!!g' > $CMD_OUT 2>&1
+        adb_cmd shell "$@" ";" echo \$? | sed -e 's![[:cntrl:]]!!g' > $CMD_OUT 2>&1
     else
-        $ADB_CMD shell $@ ";" echo \$? | sed -e 's![[:cntrl:]]!!g' > $CMD_OUT
+        adb_cmd shell "$@" ";" echo \$? | sed -e 's![[:cntrl:]]!!g' > $CMD_OUT
     fi
     # Get last line in log, which contains the exit code from the command
     RET=`sed -e '$!d' $CMD_OUT`
@@ -330,14 +377,22 @@ _adb_var_shell ()
 # or 1 (failure) otherwise.
 adb_var_shell ()
 {
-    _adb_var_shell 0 $@
+    _adb_var_shell 0 "$@"
 }
 
 # A variant of adb_var_shell that stores both stdout and stderr in the output
 # $1: Variable name
 adb_var_shell2 ()
 {
-    _adb_var_shell 1 $@
+    _adb_var_shell 1 "$@"
+}
+
+# Return the PID of a given package or program, or 0 if it doesn't run
+# $1: Package name ("com.example.hellojni") or program name ("/lib/gdbserver")
+# Out: PID number, or 0 if not running
+get_pid_of ()
+{
+    adb_cmd shell ps | $AWK_CMD -f $AWK_SCRIPTS/extract-pid.awk -v PACKAGE="$1"
 }
 
 # Check the awk tool
@@ -410,7 +465,7 @@ APP_ABIS=`get_build_var APP_ABI`
 log "ABIs targetted by application: $APP_ABIS"
 
 # Check the ADB command, and that we can connect to the device/emulator
-ADB_TEST=`$ADB_CMD shell ls`
+ADB_TEST=`adb_cmd shell ls`
 if [ $? != 0 ] ; then
     echo "ERROR: Could not connect to device or emulator!"
     echo "       Please check that an emulator is running or a device is connected"
@@ -472,6 +527,16 @@ if [ "$COMPAT_ABI" = none ] ; then
 fi
 log "Compatible device ABI: $COMPAT_ABI"
 
+# Get information from the build system
+GDBSETUP_INIT=`get_build_var_for_abi NDK_APP_GDBSETUP $COMPAT_ABI`
+log "Using gdb setup init: $GDBSETUP_INIT"
+
+TOOLCHAIN_PREFIX=`get_build_var_for_abi TOOLCHAIN_PREFIX $COMPAT_ABI`
+log "Using toolchain prefix: $TOOLCHAIN_PREFIX"
+
+APP_OUT=`get_build_var_for_abi TARGET_OUT $COMPAT_ABI`
+log "Using app out directory: $APP_OUT"
+
 # Check that the application is debuggable, or nothing will work
 DEBUGGABLE=`run_awk_manifest_script extract-debuggable.awk`
 log "Found debuggable flag: $DEBUGGABLE"
@@ -516,16 +581,6 @@ if [ $? != 0 ]; then
 fi
 log "Found device gdbserver: $DEVICE_GDBSERVER"
 
-# Get information from the build system
-GDBSETUP_INIT=`get_build_var_for_abi NDK_APP_GDBSETUP $COMPAT_ABI`
-log "Using gdb setup init: $GDBSETUP_INIT"
-
-TOOLCHAIN_PREFIX=`get_build_var_for_abi TOOLCHAIN_PREFIX $COMPAT_ABI`
-log "Using toolchain prefix: $TOOLCHAIN_PREFIX"
-
-APP_OUT=`get_build_var_for_abi TARGET_OUT $COMPAT_ABI`
-log "Using app out directory: $APP_OUT"
-
 # Find the <dataDir> of the package on the device
 adb_var_shell2 DATA_DIR run-as $PACKAGE_NAME /system/bin/sh -c pwd
 if [ $? != 0 -o -z "$DATA_DIR" ] ; then
@@ -559,7 +614,7 @@ fi
 
 if [ -n "$OPTION_LAUNCH" ] ; then
     log "Launching activity: $PACKAGE_NAME/$OPTION_LAUNCH"
-    run $ADB_CMD shell am start -n $PACKAGE_NAME/$OPTION_LAUNCH
+    run adb_cmd shell am start -n $PACKAGE_NAME/$OPTION_LAUNCH
     if [ $? != 0 ] ; then
         echo "ERROR: Could not launch specified activity: $OPTION_LAUNCH"
         echo "       Use --launch-list to dump a list of valid values."
@@ -567,11 +622,11 @@ if [ -n "$OPTION_LAUNCH" ] ; then
     fi
     # Sleep a bit, it sometimes take one second to start properly
     # Note that we use the 'sleep' command on the device here.
-    run $ADB_CMD shell sleep $DELAY
+    run adb_cmd shell sleep $DELAY
 fi
 
 # Find the PID of the application being run
-PID=`$ADB_CMD shell ps | $AWK_CMD -f $AWK_SCRIPTS/extract-pid.awk -v PACKAGE=$PACKAGE_NAME`
+PID=$(get_pid_of "$PACKAGE_NAME")
 log "Found running PID: $PID"
 if [ $? != 0 -o "$PID" = "0" ] ; then
     echo "ERROR: Could not extract PID of application on device/emulator."
@@ -590,22 +645,19 @@ if [ $? != 0 -o "$PID" = "0" ] ; then
 fi
 
 # Check that there is no other instance of gdbserver running
-GDBSERVER_PS=`$ADB_CMD shell ps | grep lib/gdbserver`
-if [ -n "$GDBSERVER_PS" ] ; then
+GDBSERVER_PID=$(get_pid_of lib/gdbserver)
+if [ "$GDBSERVER_PID" != "0" ]; then
     if [ "$OPTION_FORCE" = "no" ] ; then
         echo "ERROR: Another debug session running, Use --force to kill it."
         exit 1
     fi
     log "Killing existing debugging session"
-    GDBSERVER_PID=`echo $GDBSERVER_PS | $AWK_CMD -f $AWK_SCRIPTS/extract-pid.awk -v PACKAGE=lib/gdbserver`
-    if [ $GDBSERVER_PID != 0 ] ; then
-        run $ADB_CMD shell kill -9 $GDBSERVER_PID
-    fi
+    run adb_cmd shell kill -9 $GDBSERVER_PID
 fi
 
 # Launch gdbserver now
 DEBUG_SOCKET=debug-socket
-run $ADB_CMD shell run-as $PACKAGE_NAME lib/gdbserver +$DEBUG_SOCKET --attach $PID &
+run adb_cmd shell run-as $PACKAGE_NAME lib/gdbserver +$DEBUG_SOCKET --attach $PID &
 if [ $? != 0 ] ; then
     echo "ERROR: Could not launch gdbserver on the device?"
     exit 1
@@ -614,7 +666,7 @@ log "Launched gdbserver succesfully."
 
 # Setup network redirection
 log "Setup network redirection"
-run $ADB_CMD forward tcp:$DEBUG_PORT localfilesystem:$DATA_DIR/$DEBUG_SOCKET
+run adb_cmd forward tcp:$DEBUG_PORT localfilesystem:$DATA_DIR/$DEBUG_SOCKET
 if [ $? != 0 ] ; then
     echo "ERROR: Could not setup network redirection to gdbserver?"
     echo "       Maybe using --port=<port> to use a different TCP port might help?"
@@ -623,10 +675,13 @@ fi
 
 # Get the app_server binary from the device
 APP_PROCESS=$APP_OUT/app_process
-run $ADB_CMD pull /system/bin/app_process `native_path $APP_PROCESS`
+run adb_cmd pull /system/bin/app_process `native_path $APP_PROCESS`
 log "Pulled app_process from device/emulator."
 
-run $ADB_CMD pull /system/lib/libc.so `native_path $APP_OUT/libc.so`
+run adb_cmd pull /system/bin/linker `native_path $APP_OUT/linker`
+log "Pulled linker from device/emulator."
+
+run adb_cmd pull /system/lib/libc.so `native_path $APP_OUT/libc.so`
 log "Pulled libc.so from device/emulator."
 
 # Now launch the appropriate gdb client with the right init commands
